name: Evryway
title: Evryway 
email: hi@evryway.com
description: Shiny things for your delectation
avatar: /assets/evryway_logo.png
baseurl: ""
url: http://www.evryway.com
twitter_username: evryway
github_username: evryway

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

discus: evryway
google_analytics: UA-74411745-1

footer-links:
  email: hi@evryway.com
  twitter: evryway
  youtube: channel/UC6XE5DBPf_Eyo5clCjMHMIQ
  mastodon:
    server: mastodon.gamedev.place
    username: evryway

sass:
  style: :expanded

markdown: kramdown
highlighter: rouge
encoding: UTF-8
permalink: /:title/

keywords: VR, virtual reality, tim swan, VR prototypes, AR, augmented reality, mixed reality, holodeck

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - go.bat

include:
  - .well_known
